version: "3"

services:
  bcd-nginx:
    container_name: "bcd-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - bcd-app
    ports:
      - 80:80
    volumes:
      - ./src:/usr/app

  bcd-app:
    container_name: "bcd-app"
    build:
      context: ./docker/php
    ports:
      - 5173:5173
    volumes:
      - ./src:/usr/app
      - /usr/app/node_modules
      - /usr/app/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
